name: Netlify Deploy

on:
  schedule:
  - cron: "*/30 7-23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.netlify_rebuild }}
